### ISSUE TITLE
Flathub version being treated as unsupported

### ISSUE THREAD

**Issue by Tina-otoge** [MidflightDigital/XX--STARLiGHT--twopointzero#6]
![image](https://user-images.githubusercontent.com/9400466/143778963-1917aa5b-a362-4a00-9d4a-2b2535693c19.png)

I haven't looked at how version checking is done, but from what I can tell from this screenshot, the skin assumes my version is older than 2019 even though it's more recent, and it's able to actually extract the build date (2020 04 24) since it displays it at the bottom

It's not a big hurdle but it could be cool to not flag it as unsupported as it looks like it's possible to see the version is actually recent enough.

I use the Flathub release so it may play a role in how the version string is generated
https://github.com/flathub/com.stepmania.StepMania/

**Comment by Inorizushi** [comment]
https://github.com/MidflightDigital/XX--STARLiGHT--twopointzero/commit/c46edcf0f092c8e2f54bd21a26ddbd0bb4c006f3

Fixed, I originally had the check setup to check for Lua 5.3 OR a low version date instead of using an and statement. Please replace the branches.lua file with the current one on the repo

**Comment by Tina-otoge** [comment]
That was fast.

I can confirm the unsupported version warning does not appear anymore. Thank you!

Closing this.
